name: Contribs
on:
  workflow_dispatch
#schedule:
#    - cron:  '*/15 * * * *'
#  pull_request_target:
#    types:
#      - closed
#      - labeled

jobs:
  contribs:
    runs-on: ubuntu-latest
    name: Contribs
    steps:
      - name: Contribs
        uses: carlescufi/action-contribs@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
